#problem - https://rosalind.info/problems/subs/
#solution

def motif_finder(DNA, motif):
    motif_locations = []
    for i in range(len(DNA)-len(motif)):
        if (DNA[i:(i + len(motif))] == motif):
            motif_locations.append(i+1)
    return(motif_locations)
    
X = motif_finder("TCCAACTTGAGAGCAGTTACTTGAGGACTTGAGTACTTGAGCGGTCACTTGAGGACTTGAGCCACTTGAGCTTCTAACTTGAGGGGACGGGACTTGAGTGAAACTTGAGTAGCATACTTGAGAGCACCGCGACTTGAGAGAAACTTGAGACTTGAGCTACTTGAGTACTTGAGTCTACTTGAGACTTGAGTCACTTGAGCAAAAACTTGAGTTAGACACTTGAGATAGAACATTCAACTTGAGAGCACTTGAGAAATTTTGAAACGACTTGAGTTAGCGAGACTTGAGAAACTTGAGAACTTGAGTTTACTTGAGATGTTGTAACTTGAGACTTGAGGGAACTTGAGATCGTCGGACTTGAGCCAGACTTGAGGACTTGAGTGAACTTGAGACTTGAGACTTGAGCGCTACTTGAGCCGGAGTACTTGAGTAACTTGAGTTGCAACTTGAGCATACTTGAGCACTTGAGACGTGCGGAACTTGAGCCACTTGAGCACTTGAGGGACTTGAGGGTTGACACTTGAGGGACTTGAGGTACTTGAGACTTGAGAAACTTGAGTTGACTATTACTTGAGTACTTGAGCACTTGAGTTACAACTTGAGGAAGACTTGAGTTACTTGAGAACTTGAGTCTCACTTGAGTGATCCGAGAGACTTGAGACACTTGAGAAACTTGAGTGTGCAACTTGAGCAAATGACTTGAGTACTTGAGCACTTGAGCCACTTGAGGGTGAAGACCACTTGAGGACTTCGACTTGAGAGCTGCACTTGAGTTGAACTTGAGATCAACTTGAG", "ACTTGAGAC")
print(X)
#update the final answer format by removing commas
